services:
  postgres:
    image: postgres:16
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user_db
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5


  redis:
    image: redis:7
    container_name: redis_auth
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=nikitalaguT03
#    command: redis-server --requirepass nikitalaguT03

volumes:
  postgres_data: