server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  security:
    user:
      name: user
      password: password
jwt:
  secret: "kYpN5+MWfjZqYnmA19qzWkN528TY3KhCCMgg8SAZyT4="
  access-token-expiration: 3600000   # 1 ???
  refresh-token-expiration: 604800000 # 7 ????

